#!/usr/bin/env python3
"""Generate an Issue (request) for the next polish cycle via OpenAI critique.

This does NOT apply changes directly.
It creates a GitHub Issue labeled `moltbot` which will trigger the existing
issue-intake → PR → autonomy → merge loop.

Usage:
  OPENAI_API_KEY=... python3 scripts/moltbot_polish_cycle.py --repo anboas/Whitepaper --paper agentic-force-creation

Behavior:
- Reads papers/<paper>/INTENT.md and tex/paper.tex
- Calls OpenAI to produce STRICT JSON critique
- Converts top priority_fixes into a single issue body
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
from pathlib import Path

import requests


def sh(*cmd: str) -> str:
    return subprocess.check_output(list(cmd), text=True).strip()


def pick_model(api_key: str) -> str:
    try:
        r = requests.get("https://api.openai.com/v1/models", headers={"Authorization": f"Bearer {api_key}"}, timeout=20)
        if r.status_code < 300:
            ids = [m.get("id", "") for m in (r.json().get("data") or []) if isinstance(m, dict)]
            cand = [i for i in ids if i and ("gpt" in i.lower())]
            for pref in ("gpt-5", "gpt-4.1"):
                for i in cand:
                    if i.lower().startswith(pref):
                        return i
    except Exception:
        pass
    return "gpt-5"


def openai_json(api_key: str, model: str, intent_md: str, tex: str) -> dict:
    prompt = {
        "intent_md": intent_md,
        "current_paper_tex": tex,
    }
    sysmsg = (
        "You are a ruthless-but-helpful editor. "
        "Output STRICT JSON only (no markdown). "
        "If you cannot comply, output an empty JSON object {}."
    )

    payload = {
        "model": model,
        "input": [
            {"role": "system", "content": sysmsg},
            {"role": "user", "content": json.dumps(prompt)},
        ],
    }

    rr = requests.post(
        "https://api.openai.com/v1/responses",
        headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
        json=payload,
        timeout=180,
    )
    rr.raise_for_status()
    data = rr.json()
    out_text = None
    for item in data.get("output", []):
        if item.get("type") == "message":
            for c in item.get("content", []):
                if c.get("type") == "output_text":
                    out_text = c.get("text")
                    break
    if not out_text:
        return {}
    out_text = out_text.strip()
    try:
        return json.loads(out_text)
    except Exception:
        # best effort: find first {...}
        i = out_text.find("{")
        j = out_text.rfind("}")
        if i >= 0 and j > i:
            try:
                return json.loads(out_text[i : j + 1])
            except Exception:
                return {}
        return {}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", required=True)
    ap.add_argument("--paper", required=True)
    ap.add_argument("--max_fixes", type=int, default=6)
    args = ap.parse_args()

    api_key = os.environ.get("OPENAI_API_KEY", "").strip()
    if not api_key:
        raise SystemExit("Missing OPENAI_API_KEY")

    root = Path(__file__).resolve().parents[1]
    paper_dir = root / "papers" / args.paper
    intent = (paper_dir / "INTENT.md").read_text(encoding="utf-8", errors="ignore")
    tex = (paper_dir / "tex" / "paper.tex").read_text(encoding="utf-8", errors="ignore")

    model = pick_model(api_key)
    critique = openai_json(api_key, model, intent, tex)

    stop = critique.get("stop_condition") or {}
    if stop.get("is_polished") is True:
        # Write a marker so cron can stop generating more issues.
        (root / ".polish_done").write_text("polished\n", encoding="utf-8")
        print("POLISHED: stop_condition.is_polished=true")
        return 0

    fixes = (critique.get("priority_fixes") or [])[: args.max_fixes]
    title = f"Polish cycle: {args.paper} (iterate)"

    body_lines = [
        f"Paper: {args.paper}",
        "",
        "Request:",
        "Apply the following targeted improvements (generated by critique pass).",
        "",
        "```json",
        json.dumps(critique, indent=2)[:12000],
        "```",
        "",
        "Constraints:",
        "- Prefer additive / localized changes.",
        "- Keep LaTeX compiling.",
        "- No invented citations.",
    ]

    body = "\n".join(body_lines)

    # Create issue
    sh(
        "gh",
        "issue",
        "create",
        "--repo",
        args.repo,
        "--title",
        title,
        "--label",
        "moltbot",
        "--body",
        body,
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
